[tool.poetry]
name = "CAPEsolo"
version = "0.4.0"
description = "Standalone CAPEMON"
authors = ["enzok <7831008+enzok@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
wxpython = "^4.2.1"
pywin32 = "^306"
bson = "^0.5.10"
yara-python = "^4.5.0"
pefile = "^2024.8.26"
pycryptodomex = "^3.20.0"
cryptography = "^43.0.0"
requests = "^2.31.0"
dnfile = "^0.15.0"
SFlock2 = {version = "0.3.66", extras = ["shellcode","win32"]}
greenlet = "^3.1.1"
gevent = "^24.2.1"
dnspython = "^2.6.1"
tldextract = "^5.1.2"
netstruct = "^1.1.2"

[tool.poetry.scripts]
CAPEsolo = "CAPEsolo.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
